### PR TITLE
Added option to individually override the AppID and ParentID of games…

### PR DESCRIPTION
**Pull request by caballinger**
…. Useful for some games that do not have a store page (e.g. Left 4 Dead 2 Beta).

### CODE REVIEW

**Comment by Theo47** [comment]
Couldn't you already edit the ParentID of games?

**Comment by caballinger** [comment]
I thought that at first as well, but it turns out not quite (I think). I originally attempted to use the parentID, and briefly reviewed the code before implementing this solution, so I could be mistaken. But as I recall, the parentID is something that is scraped from a games page, and gets updated whenever the program launches or the user re-scrapes/updates their DB. If the game has no page, the scraper overwrites the ParentID with a 0 in the DB, even if the user has made a manual edit. We COULD disable updating non-zero parentIDs with 0 I suppose, but honestly that makes me a bit more nervous, because there may cases where that's valid behavior (What if a game has a valid parent ID, then the game and its parent get removed from steam?). Additionally, I can imagine (admittedly rare) cases where a user might want to do a manual overrideID, even IF the game has a valid store page or parentID. If you'd like, I can re-attempt to use the parentID and review the code again to confirm this is the case.

**Comment by Theo47** [comment]
You are right, parentID is overwritten when you update the database from AppInfo.
In that case though i think it makes more sense to prevent it from getting overwritten rather than adding a new, almost-duplicate field.

>What if a game has a valid parent ID, then the game and its parent get removed from steam?

Not sure what would happen in that case or what we would want to happen. If we wanted to keep the old parent id and now it would be updated with 0 then your suggested fix works.

If we don't want to go the "disable updating non-zero parentIDs with 0" route (i am not sure what the edge cases would be) then we could introduce a hidden (does not appear in edit games) boolean field. It is set to true if the user modifies the ParentId field and if it is true it prevents the ParentId from updating. Probably set it to false if users puts an empty value as ParentId.

Is there a case where a user would want to change a non-zero ParentId to 0? If there is then your override field also doesn't solve that problem.

**Comment by caballinger** [comment]
Hm, I think you might be right, although I would make the boolean editable. At the very least you'd want to make it viewable, so the user knows what implicit behavior is going on under the hood when they change the value, but then you end up with users confused on how to "disable" that field. Better to make it a very explicit and intentional action imo.

To slightly expand on the idea, maybe we should two booleans: a viewable (but un-editable) bool called "Missing Store Page" and a editable bool called "Ignore Store Page". When the scraper detects that a game is missing a store page (which I think it already basically does), it sets the Missing bool to true. If either of these bools are true, then the scraper will only update the "Missing" bool when the game info is scraped. If only the Missing bool is set, then the user can change the parentID, and the DB will continue using the user's input UNTIL the store page returns (as has occurred for some games). This would also allow us to create an auto-cat for games that were (possibly) removed from steam. If the "Ignore" boolean is enabled, then the scraper continues to ignore the store page and uses the manually set parentID, until the user decides to set the bool to false.

**Comment by Theo47** [comment]
I'd consider the implicit behavior pretty obvioius. If i press edit game, change a field then press save, i'd expect my changes to be saved. Do i really need to know how the save occurs under the hood? In fact wouldn't it end up being more confusing having all these additional checkboxes? Especially if we try taking the same approach with other fields.

I guess how to restore the default parent id may be less obvious but in that case it may be more intuitive to add a "restore to defaults" button next to the save/cancel buttons instead.

I took a better look and what you suggest with the "missing store page" is the default behavior right now. If a game has no steam store page then the database will keep your changes rather than overwriting them with a blank string when re-scraping it. The only exception to this was parent ID and platforms since those update from a local steam file rather than the store page.

Would the "Ignore store page" checkbox affect only the parentID field or every field?

At this point i think we should go with the "disable updating non-zero parentIDs with 0" approach you suggested earlier. That would make Parent Id behave like the rest of the fields in the database (consistent behavior). 

You said you can imagine cases where a game will have a valid parent id but the user will still want to override it.
Can you give some examples? I tried thinking of such cases but i couldn't come up with any.

**Comment by caballinger** [comment]
So just to make sure I'm understanding correctly, the next two points in reference to the following suggestion:
> we could introduce a hidden (does not appear in edit games) boolean field. It is set to true if the user modifies the ParentId field and if it is true it prevents the ParentId from updating. 

> I'd consider the implicit behavior pretty obvioius. If i press edit game, change a field then press save, i'd expect my changes to be saved. Do i really need to know how the save occurs under the hood?
My main concern here is with the user not realizing that editing the value would mean that field would no longer be updated automatically, even IF there was a valid ID. 

> At this point i think we should go with the "disable updating non-zero parentIDs with 0" approach you suggested earlier. That would make Parent Id behave like the rest of the fields in the database (consistent behavior).
I don't think that's entirely consistent with other fields. To keep it consistent, we'd just want the parentID to not update when the store page is missing. Which seems like it's actually an easier change to make, since that condition is basically already laid out. Otherwise, if you want consistent behavior, you have either have to: 1) make it so that if the user edits ANY field, then ALL fields will no longer be updated, or 2) add a bool for each field, so any field the user edits will no longer be updated. 

> Would the "Ignore store page" checkbox affect only the parentID field or every field?
I was thinking every field. More or less, that checkbox should mean "I want to handle this entire entry manually".


> You said you can imagine cases where a game will have a valid parent id but the user will still want to override it. Can you give some examples?
Honestly I can only think of one useful use-case: when you have a series/sequels that are basically the same game, but yet have different tags/categorization on the steam page (e.g. Sam & Max, Agarest). If you want to make sure every game in the series have the same categories/tags, you would just point the parentID of all games in the series to one other game in the series.

I suppose in most of these cases, since these are separate games, the parentID is going to be zero (i don't know if there are any cases where this might be non-zero), the "disable updating non-zero parentIDs with 0"  might work. But then we run into the problem of consistent behavior between fields.

**Comment by caballinger** [comment]
After thinking a bit more on it, I have an additional thought on the "Stop updating field when user does a manual edit" suggestion. I think my main issue is that there's no to way to differentiate between fields/entries that are automatically updated, and those that are not updated because they were manually edited. If the the field/entry is highlighted/bold or something after the user manually edits a field, it would at least indicate to the user that there is something "special" about those fields, and would make the idea much better.

**Comment by Theo47** [comment]
> I don't think that's entirely consistent with other fields. To keep it consistent, we'd just want the parentID to not update when the store page is missing. Which seems like it's actually an easier change to make, since that condition is basically already laid out. Otherwise, if you want consistent behavior, you have either have to: 1) make it so that if the user edits ANY field, then ALL fields will no longer be updated, or 2) add a bool for each field, so any field the user edits will no longer be updated. 

The other fields do not update if the new value would be null. It is just that most games that have store pages also have genre and tags so the difference isn;t obvious. For example the conditon for release date is: `if (!string.IsNullOrEmpty(other.SteamReleaseDate))  SteamReleaseDate = other.SteamReleaseDate;`
So parent id not updating with new null values would be consistent behavior. (`if (other.ParentId > 0) ParentId = other.ParentId;`)

> After thinking a bit more on it, I have an additional thought on the "Stop updating field when user does a manual edit" suggestion. I think my main issue is that there's no to way to differentiate between fields/entries that are automatically updated, and those that are not updated because they were manually edited. If the the field/entry is highlighted/bold or something after the user manually edits a field, it would at least indicate to the user that there is something "special" about those fields, and would make the idea much better.

We could do that but it would probably look strange if parent id was the only field that got bold when modified. We could do it for every field but that would require adding 15 new variables for each db entry so we can monitor modifications on each field. Seems a lot of work just to handle a rare case for parent id that may or may not exist, especially when the alternative would just be a line of code in 2-3 places in the program.

**Comment by Theo47** [comment]
Actually the `if (other.ParentId > 0) ParentId = other.ParentId;` code already exists on line 419 of GameDB.cs preventing parentid from been overwritten when updating from store page.

So it was probably an oversight that something similar wasn't added when it updates from AppInfo.

**Comment by caballinger** [comment]
Yeah, now that I've had my morning coffee and had a chance to look at the code again, I think you are right again. At the very least, not overriding a non-zero parentID with zero should be implemented as a bugfix.

Making manual changes to the DB and preventing updates from overriding the manual changes is a much bigger addition. Your suggestions have given me a lot to think about, so I'll set that aside while I'll consider everything and try to refine the idea.

I was thinking it might be a good idea to add a bool for tracking games with missing store pages, since that should be simple to implement and might make for a desirable auto-cat. But I was also thinking that for finding "Removed games from steam", it might be more accurate to scrape steamdb.info. That's a much bigger addition though.

Anywho, if we're agree'd on the parentID fix, I'll close this request while I work on the other ideas.

**Comment by Theo47** [comment]
>Anywho, if we're agree'd on the parentID fix, I'll close this request while I work on the other ideas.

Yeah i considered this a bug and i already fixed it.

>Making manual changes to the DB and preventing updates from overriding the manual changes is a much bigger addition. Your suggestions have given me a lot to think about, so I'll set that aside while I'll consider everything and try to refine the idea.

In this case we want to consider how to handle updates for each field.
Do we keep the user's modifications, update it with the newest data from the store, show a prompt to the user and and ask him to decide or attempt to merge the changes in some intelligent way?

For fields like release date the answer seems simple. We keep the user's modification. After all i doubt the release date for a game would change in steam store.

But what about fields like flags? Let's take the following example.
Game A has the following flags: Single-Player, Partial Controller Support
User doesn't like the controller support and changes the flags to: Single-Player
Now a new update comes out and achievements are added to the game. 
So store flags are now: Single-Player, Partial Controller Support, Achievements.

What should we do in this case?
We can keep the user's modification but that way the user won;t know Achievements were added to the game.
We can use the store information but now the game will also be listed as Partial Controller Support which the user previously removed.
We can show a promt to the user asking him what he wants to do but that may get annoying if many games had many changes.
We could try to merge the changes so the new flags would be "Single-Player, Achievements" but that would require more effort programming trying to take into account the various cases that might occur.

Just some food for thought.

**Comment by Theo47** [comment]
I know this is over but i wanted to say that turns out i was confused too. I thought that adding new 15 new variables to track each modifications on each field meant that we would need to save (15 x number of games) new values on the database. But we don't save a value unless it differs from the default. That means that if the user does no modifications the database would remain the same as it is right now while if he did 5 modifications we would just need to save 5 new values on the database.
So it doesn't sound the big deal i thought it did at first. My bad.

**Comment by caballinger** [comment]
Ah, good catch. I knew that's the way it worked for other fields in the DB, but failed to catch that as well. Still kicking it around as an idea, but for me personally, there are a few other enhancements that I think would be more useful since the bugfix fixed most of my problems anyway.

**Pull request closed without merging**
