### PR TITLE
Minor Project Fixes

### PR DESCRIPTION
**Pull request by mvegter**
- Use the correct .gitignore
- Added .gitattributes
- Removed Packages folder (ignored by .gitignore), as they are restored with NuGet
- Upgraded to .NET Framework v4.7
- Bumped project version to v0.7.4.0
- Removed duplicate Readme
- Update README (.md and .txt)

### CODE REVIEW

**Comment by Theo47** [comment]
Not sure why the version bump but the rest looks good.

**Comment by mvegter** [comment]
@Theo47 Fixing the nuget and .ignore is, I believe, considered a patch so `v0.7.3.1`. And changing the framework is a minor change, thus version `v0.7.4.0`, as patch is reset to `0` after a new minor change.

Might be an idea to completely move towards `Semantic Versioning 2.0.0` (http://semver.org/), and use it accordingly.

**Comment by Theo47** [comment]
I see. I usually update the version just before each release rather than every few commits.

I'd consider the framework update to be a minor change if it introduces new functionality we are taking advantage of or a patch if it is mostly bug fixes or has no noticeable effect to the application at all.
Since i wasn't aware of what the new functionality was, i guess i was classifying it as a patch.

I guess i just sticked to this versioning system since it was what the original used.

**Comment by mvegter** [comment]
@Theo47 

Github recommends using `Semantic versioning` as they state in the `draft a bew release` menu. And in case you agree on this, I would recommended publishing a version `1.0.0` and from that moment use version increasement according to `Semantic Versioning 2.0.0` (http://semver.org/).

On a side note: Creating a discord server to have a chat about how you want to approach this project might help for existing and new contributors. And it might be a good idea to have more collaborators, to help with the issues and publishing releases.

**Comment by Theo47** [comment]
I'd say a 1.0.0 release is long overdue (from before i even started working on this project). It is just that judging each of my releases individually, i didn't consider them worthy of a 1.0.0 bump so i ended up never doing one.

As for the versioning system, i consider that a minor detail so i don't care which one we are using. Either one works fine for me.

Before i address the rest, i should state that right now i am closer to maintaining the project rather than actively developing it. I'll just come back 2-3 times a year and do some bug fixes. If i have any time left after that, i may add a new feature or two. The rest of the year i'll more or less ignore this project.

With that in mind i'd say i prefer seeing bug reports and suggestions as issues rather than on discord. If i come back 2 months later and it is an issue, i'll see it and fix it. If it is on discord then it would probably be buried over the newer posts and get lost.

For conversations like the one we have right now, i guess discord might work better.

As for more contributors/collaborators, they are more than welcome, if anyone is interested.

**Comment by mvegter** [comment]
@Theo47 I added you on Steam, so it might be easier to have a chat there.

**Pull request merged**
