### PR TITLE
Cleanup in a few files and some null checks

### PR DESCRIPTION
**Pull request by mvegter**

### CODE REVIEW

**Comment by mvegter** [comment]
@Theo47 Thanks for the merge. I would suggest that you add your name to the modified headers as well, as in `Modified work Copyright 2017 (First Name) (Last Name) and Martijn Vegter.`, of course if you want to. 

P.S.
It is actually legally, or atleast by the GPL-3.0 license, required that you put a notice saying this is a modified version of `rallion/depressurizer`.

> 5. a) The work must carry prominent notices stating that you modified it, and giving a relevant date.
https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by Theo47** [comment]
I see.

I'll do that later then.

**Comment by Theo47** [comment]
Apparently this was creating a few bugs.

Since it was mostly cleanup fixes, i decided that the easy solution was to revert the merge.

Sorry about that.

**Comment by mvegter** [comment]
What kind of bugs? 

All changes should check for null references or code cleanup which doesn't change the code logic.

**Comment by Theo47** [comment]
I only found 2 bugs but i was afraid there may be more.

1) original:

        public virtual string DisplayName
        {
            get
            {
                string displayName = Name;
                if (Filter != null) displayName += "*";
                return displayName;
            }
        }
new:
`public virtual string DisplayName => Filter != null ? (Name += "*") : Name;`

New code kept adding a "*" to Name, each time DisplayName was called.

2) On AutoCatUserScore.cs ~lines 196-198
```
    List<UserScoreRule> rules = new List<UserScoreRule>();
            if (rules.Count > 0)
        {
```
rules.Count is always 0 at above code so the loop never run.

**Comment by mvegter** [comment]
@Theo47 About the DisplayName bug, what does it actually present, as I have not seen any autocats with a `*` behind their name. The only name that switch between nothing and a `*` is the profile name.

**Pull request merged**
